version: "3.5"
services:
  attendance-client:
    image: attendance-client:latest
    container_name: attendance-client
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
    networks:
      attendance-system-network:
        aliases:
          - attendance-client

networks:
  attendance-system-network:
    external:
      name: attendance-system-network
